# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e56aa33446b2885c7e861796092b4150bb832e7395743e38f7582e3b051dc95d953b74483e4b9e352c2af4fc319321d03b0b0b179dac5ee04c3fa76dbbdf0e3

test:
  secret_key_base: e5fb815ef2cfcf5e4bda8e63eb672962d18e2a3f0c695ddbb6f99d8bb159d559a0d1631ed57e500756dc841bbcbdfcc887047f0a7c43a88a9009a856a811a454

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
